version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2fly
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "7000:7000"
      - "8000:8000"
    volumes:
      - ./config.json:/etc/v2ray/config.json
    command: "run -config=/etc/v2ray/config.json"
