version: '3'
services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates:/etc/nginx/templates
      - ./hello:/hello
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    extra_hosts:
      - "host.docker.internal:host-gateway"

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email mohamad.darghah@gmail.com --agree-tos --no-eff-email
             -d mammadsh.ir
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
